version: '3.8'

services:
  frontend:
    build: .
    container_name: 3d-chat-frontend
    ports:
      - "3001:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
